all: db_con close_com gps payment admin client pole car

db_con:
	cd DatabaseConnector && make

close_com:
	cd CloseCommunication && make

gps:
	cd CloseCommunication && make 

payment:
	cd Payment && make

admin:
	cd AdminApplication && make

client:
	cd ClientApplication && make

pole:
	cd Pole && make

car:
	cd CarModule && make
