all: pay close_com gps db_con admin client pole car 

pay:
	cd Payment && rm -rf *.o && make

close_com:
	cd CloseCommunication && rm -rf *.o && make

gps:
	cd GPS_Tracker && rm -rf *.o && make 

admin:
	cd AdminApplication && rm -rf *.o && make

client:
	cd ClientApplication && rm -rf *.o && make

pole:
	cd Pole && rm -rf *.o && make

car:
	cd CarModule && rm -rf *.o && make

db_con:
	cd DatabaseConnector && rm -rf *.o && make
