../dll/CloseCommunication.dll : ICloseCommunication.o
	g++ -shared -o ../dll/CloseCommunication.dll ICloseCommunication.o

ICloseCommunication.o : ICloseCommunication.cpp
	g++ -c ICloseCommunication.cpp